---
apiVersion: v1
kind: Namespace
metadata:
  name: lms-production
  labels:
    name: lms-production
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: lms-development
  labels:
    name: lms-development
    environment: development
